#!/bin/bash
set -e
if ! [ -x "$(command -v git)" ]; then
  echo This extension requires jt be installed and available on the PATH. You can install it with:
  if [[ $OSTYPE == 'darwin'* ]]; then
    echo 'brew tap StevenACoffman/jt'
    echo 'brew install jt'
  else 
    echo go install github.com/StevenACoffman/jt
  fi
  exit 1
fi
jt "$@"